# Generated by Django 5.1.6 on 2025-03-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='type',
            field=models.CharField(choices=[('Ingreso', 'Ingreso'), ('Gasto', 'Gasto')], default=1, max_length=7),
            preserve_default=False,
        ),
    ]
