# Generated by Django 5.1.6 on 2025-03-09 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_report_balance_alter_report_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='expenses',
            new_name='expense',
        ),
        migrations.AlterField(
            model_name='report',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='report',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización'),
        ),
    ]
